# Generated by Django 5.0.2 on 2024-05-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
