# Generated by Django 5.0.2 on 2024-05-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0006_student_address_student_email_student_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(choices=[('Fintech', 'Fintech'), ('Business IT', 'Business IT'), ('Computer Science', 'Computer Science')], max_length=100),
        ),
    ]
