# Generated by Django 5.0.2 on 2024-05-03 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0007_alter_student_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
